In [2]:
import pandas as pd
%matplotlib inline
import matplotlib.pyplot as plt

In [3]:
## Read one file and adjust 'skiprows'

file = "output1.xlsx"
file_avg = pd.read_excel(file)
file_avg.head()

,Day,Site Key,Site Name,Ad Spend,Impressions,Clicks,Room Orders,Room Revenue*,Room Nights,Measurable Impressions,Viewable Impressions,Ad Spend_avg,Impressions_avg,Clicks_avg,Room Orders_avg,Room Revenue*_avg,Room Nights_avg,Measurable Impressions_avg,Viewable Impressions_avg
0,2018-01-31,2761561,Google AdWords,8440.200000,68590.0,2941.0,56,62174.357143,186,NaN,NaN,16710.325806,91059.870968,3548.161290,58.741935,60025.879608,176.290323,NaN,NaN
1,2018-01-31,1556720,www.sojern.com,4436.770000,887354.0,467.0,17,24563.160714,66,873600.0,485920.0,3890.311935,778063.032258,431.774194,16.225806,19018.430876,53.096774,767137.935484,437188.741935
2,2018-01-31,1506491,Adara Media,2893.200645,299496.0,30.0,3,2824.401786,8,288742.0,66107.0,3225.807258,343843.548387,117.935484,7.322581,8062.751728,21.161290,345675.033333,168323.866667
3,2018-01-31,1506505,TripAdvisor,2384.538000,91713.0,44.0,8,6532.580357,20,86825.0,63637.0,2721.513935,104673.612903,77.129032,7.967742,6828.093894,21.516129,101060.870968,74513.193548
4,2018-01-31,2810812,Bing Ads,2122.820000,24091.0,735.0,14,10566.758929,37,NaN,NaN,2589.757742,26775.645161,761.741935,8.741935,8995.154666,26.806452,NaN,NaN

In [4]:
## Combine all files via loop and store it as a combined data frame called 'all_data'

# file_list = ["2. A Rooms_Marketing_20180101-20180331.xlsx", "2. A Rooms_Marketing_20180401-20180630.xlsx", \
#              "2. A Rooms_Marketing_20180701-20180930.xlsx", "2. A Rooms_Marketing_20181001-20181231.xlsx", \
#              "2. A Rooms_Marketing_20190101-20190331.xlsx","2. A Rooms_Marketing_20190401-20190630.xlsx", \
#              "2. A Rooms_Marketing_20190701-20190930.xlsx"]


# all_data = pd.DataFrame()

# for file in file_list:
#     df = pd.read_excel(file, skiprows=6)
#     all_data = all_data.append(df, ignore_index=True)

In [5]:
## Check if it worked and overall stats

file_avg.head()
# file_avg.describe()

,Day,Site Key,Site Name,Ad Spend,Impressions,Clicks,Room Orders,Room Revenue*,Room Nights,Measurable Impressions,Viewable Impressions,Ad Spend_avg,Impressions_avg,Clicks_avg,Room Orders_avg,Room Revenue*_avg,Room Nights_avg,Measurable Impressions_avg,Viewable Impressions_avg
0,2018-01-31,2761561,Google AdWords,8440.200000,68590.0,2941.0,56,62174.357143,186,NaN,NaN,16710.325806,91059.870968,3548.161290,58.741935,60025.879608,176.290323,NaN,NaN
1,2018-01-31,1556720,www.sojern.com,4436.770000,887354.0,467.0,17,24563.160714,66,873600.0,485920.0,3890.311935,778063.032258,431.774194,16.225806,19018.430876,53.096774,767137.935484,437188.741935
2,2018-01-31,1506491,Adara Media,2893.200645,299496.0,30.0,3,2824.401786,8,288742.0,66107.0,3225.807258,343843.548387,117.935484,7.322581,8062.751728,21.161290,345675.033333,168323.866667
3,2018-01-31,1506505,TripAdvisor,2384.538000,91713.0,44.0,8,6532.580357,20,86825.0,63637.0,2721.513935,104673.612903,77.129032,7.967742,6828.093894,21.516129,101060.870968,74513.193548
4,2018-01-31,2810812,Bing Ads,2122.820000,24091.0,735.0,14,10566.758929,37,NaN,NaN,2589.757742,26775.645161,761.741935,8.741935,8995.154666,26.806452,NaN,NaN

In [6]:
# Looking for null values

file_avg.isna().head()

,Day,Site Key,Site Name,Ad Spend,Impressions,Clicks,Room Orders,Room Revenue*,Room Nights,Measurable Impressions,Viewable Impressions,Ad Spend_avg,Impressions_avg,Clicks_avg,Room Orders_avg,Room Revenue*_avg,Room Nights_avg,Measurable Impressions_avg,Viewable Impressions_avg
0,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,True,True
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,True,True

In [7]:
## Dropped Null values from ad spend and revenue column as a start

# clean_simple_df = all_data.dropna(subset=['Ad Spend', 'Room Revenue*'])

# clean_simple_df.isna().head()

In [8]:
# X = all_data["weight"].values.reshape(-1, 1)
# y = all_data["size"].values.reshape(-1, 1)


X = file_avg[["Ad Spend_avg", "Impressions_avg", "Clicks_avg"]]
y = file_avg["Room Revenue*_avg"].values.reshape(-1, 1)

print("Shape: ", X.shape, y.shape)

Shape:  (10923, 3) (10923, 1)

In [9]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.model_selection import train_test_split

model = LinearRegression()

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

In [10]:
model.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [11]:
# Use our model to make predictions
predicted = model.predict(X_test)

# Score the predictions with mse and r2
mse = mean_squared_error(y_test, predicted)
r2 = r2_score(y_test, predicted)

print(f"Mean Squared Error (MSE): {mse}")
print(f"R-squared (R2 ): {r2}")

Mean Squared Error (MSE): 25583309.57781327
R-squared (R2 ): 0.8575393246154386

In [12]:
model.score(X, y)

0.8567861292466825

In [13]:
model.score(X_train, y_train)
model.score(X_test, y_test)

0.8575393246154386